sudo: required
language: generic
script: make

install:
    - sudo apt-get install gnat
    - wget https://github.com/tgingold/ghdl/archive/master.zip
    - unzip -qq master.zip
    - cd ghdl-master
    - ./configure --prefix=/usr/local
    - make
    - sudo make install
    - cd ..
    - rm -R ghdl-master master.zip
